#### Prepare rules for all the data sets

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("C:\\DataScience\\Assignment\\Recommendation System\\book.csv", encoding='latin-1')
df

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

## EDA and Visualization

In [3]:
df.drop(columns='Unnamed: 0', inplace= True)

In [4]:
df.rename(columns={'User.ID':'Id', 'Book.Title':'Book', 'Book.Rating':'Rating'}, inplace= True)
df

Id                                               Book  Rating
0     276726                                Classical Mythology       5
1     276729                                       Clara Callan       3
2     276729                               Decision in Normandy       6
3     276736  Flu: The Story of the Great Influenza Pandemic...       8
4     276737                             The Mummies of Urumchi       6
...      ...                                                ...     ...
9995  162121       American Fried: Adventures of a Happy Eater.       7
9996  162121                              Cannibal In Manhattan       9
9997  162121                    How to Flirt: A Practical Guide       7
9998  162121                                           Twilight       8
9999  162129                       Kids Say the Darndest Things       6

[10000 rows x 3 columns]

In [5]:
df.Id.nunique()

2182

In [6]:
df.Book.nunique()

9659

In [7]:
df.duplicated().sum()

2

In [8]:
df = df.drop_duplicates(subset=['Id', 'Book'])

In [9]:
df

Id                                               Book  Rating
0     276726                                Classical Mythology       5
1     276729                                       Clara Callan       3
2     276729                               Decision in Normandy       6
3     276736  Flu: The Story of the Great Influenza Pandemic...       8
4     276737                             The Mummies of Urumchi       6
...      ...                                                ...     ...
9995  162121       American Fried: Adventures of a Happy Eater.       7
9996  162121                              Cannibal In Manhattan       9
9997  162121                    How to Flirt: A Practical Guide       7
9998  162121                                           Twilight       8
9999  162129                       Kids Say the Darndest Things       6

[9993 rows x 3 columns]

In [10]:
df['Rating'].value_counts()

8     2282
7     2074
10    1731
9     1492
5     1006
6      920
4      237
3      146
2       62
1       43
Name: Rating, dtype: int64

In [11]:
df.sort_values('Id')

Id                                               Book  Rating
2399       8                            Ancient Celtic Romances       5
2405       8                                  The Art Of Celtia       7
2404       8                            The Celts Activity Book       6
2400       8  The Western way: A practical guide to the West...       5
2402       8                                           Truckers       5
...      ...                                                ...     ...
2393  278854                         A corrente de Trewis Scott       7
2394  278854                                      As valkÃ­rias       7
2395  278854      La crÃ³nica del PerÃº (CrÃ³nicas de AmÃ©rica)       7
2396  278854                                Blast From the Past       7
2397  278854     A Treasury of Irish Myth, Legend, and Folklore       6

[9993 rows x 3 columns]

## Model Building

In [12]:
pivot = df.pivot(index='Id', columns= 'Book', values='Rating')
pivot

Book     Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
Id                                                                         
8                        NaN                                         NaN   
9                        NaN                                         NaN   
10                       NaN                                         NaN   
12                       NaN                                         NaN   
14                       NaN                                         NaN   
...                      ...                                         ...   
278846                   NaN                                         NaN   
278849                   NaN                                         NaN   
278851                   NaN                                         NaN   
278852                   NaN                                         NaN   
278854                   NaN                                         NaN   

Book     Repairing PC Drives &amp  '48  \
Id                                       
8                             NaN  NaN   
9                             NaN  NaN   
10                            NaN  NaN   
12                            NaN  NaN   
14                            NaN  NaN   
...                           ...  ...   
278846                        NaN  NaN   
278849                        NaN  NaN   
278851                        NaN  NaN   
278852                        NaN  NaN   
278854                        NaN  NaN   

Book    'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
Id                                                                              
8                                                     NaN                       
9                                                     NaN                       
10                                                    NaN                       
12                                                    NaN                       
14                                                    NaN                       
...                                                   ...                       
278846                                                NaN                       
278849                                                NaN                       
278851                                                NaN                       
278852                                                NaN                       
278854                                                NaN                       

Book    ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
Id                                                                     
8                                                     NaN              
9                                                     NaN              
10                                                    NaN              
12                                                    NaN              
14                                                    NaN              
...                                                   ...              
278846                                                NaN              
278849                                                NaN              
278851                                                NaN              
278852                                                NaN              
278854                                                NaN              

Book    01-01-00: A Novel of the Millennium  \
Id                                            
8                                       NaN   
9                                       NaN   
10                                      NaN   
12                                      NaN   
14                                      NaN   
...                                     ...   
278846                                  NaN   
278849                                  NaN   
278

In [13]:
pivot.fillna(0, inplace=True)
pivot

Book     Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
Id                                                                         
8                        0.0                                         0.0   
9                        0.0                                         0.0   
10                       0.0                                         0.0   
12                       0.0                                         0.0   
14                       0.0                                         0.0   
...                      ...                                         ...   
278846                   0.0                                         0.0   
278849                   0.0                                         0.0   
278851                   0.0                                         0.0   
278852                   0.0                                         0.0   
278854                   0.0                                         0.0   

Book     Repairing PC Drives &amp  '48  \
Id                                       
8                             0.0  0.0   
9                             0.0  0.0   
10                            0.0  0.0   
12                            0.0  0.0   
14                            0.0  0.0   
...                           ...  ...   
278846                        0.0  0.0   
278849                        0.0  0.0   
278851                        0.0  0.0   
278852                        0.0  0.0   
278854                        0.0  0.0   

Book    'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
Id                                                                              
8                                                     0.0                       
9                                                     0.0                       
10                                                    0.0                       
12                                                    0.0                       
14                                                    0.0                       
...                                                   ...                       
278846                                                0.0                       
278849                                                0.0                       
278851                                                0.0                       
278852                                                0.0                       
278854                                                0.0                       

Book    ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
Id                                                                     
8                                                     0.0              
9                                                     0.0              
10                                                    0.0              
12                                                    0.0              
14                                                    0.0              
...                                                   ...              
278846                                                0.0              
278849                                                0.0              
278851                                                0.0              
278852                                                0.0              
278854                                                0.0              

Book    01-01-00: A Novel of the Millennium  \
Id                                            
8                                       0.0   
9                                       0.0   
10                                      0.0   
12                                      0.0   
14                                      0.0   
...                                     ...   
278846                                  0.0   
278849                                  0.0   
278

In [14]:
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine

In [15]:
distance = pairwise_distances(pivot, metric='cosine')
distance

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [16]:
similarity = 1 - distance
similarity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [17]:
sim = pd.DataFrame(similarity)
sim

0     1     2     3     4     5     6     7     8     9     ...  2172  \
0      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2177   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2178   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2179   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      2173  2174  2175  2176  2177  2178  2179  2180  2181  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2177   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0  
2178   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0  
2179   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  

[2182 rows x 2182 columns]

In [18]:
np.fill_diagonal(sim.values, 0)

In [19]:
sim.index = df.Id.unique()
sim.columns = df.Id.unique()
sim

276726  276729  276736  276737  276744  276745  276747  276748  \
276726     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...     ...     ...     ...     ...     ...     ...     ...   
162107     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162109     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162113     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162121     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
162129     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

        276751  276754  ...  162085  162091  162092  162095  162103  162107  \
276726     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276729     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276736     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276737     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
276744     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
...        ...     ...  ...     ...     ...     ...     ...     ...     ...   
162107     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162109     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162113     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162121     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
162129     0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

        162109  162113  162121  162129  
276726     0.0     0.0     0.0     0.0  
276729     0.0     0.0     0.0     0.0  
276736     0.0     0.0     0.0     0.0  
276737     0.0     0.0     0.0     0.0  
276744     0.0     0.0     0.0     0.0  
...        ...     ...     ...     ...  
162107     0.0     0.0     0.0     0.0  
162109     0.0     0.0     0.0     0.0  
162113     0.0     0.0     0.0     0.0  
162121     0.0     0.0     0.0     0.0  
162129     0.0     0.0     0.0     0.0  

[2182 rows x 2182 columns]

In [20]:
sim.idxmax(1)[0:30]

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
276745    276726
276747    276726
276748    161677
276751    276726
276754    276726
276755    276726
276760    276726
276762    276726
276768    276726
276772      1491
276774    278543
276780    276726
276786    276726
276788    276726
276796    276726
276798    276726
276800    276726
276804    276726
276808    276726
276811    276726
276812    277533
276813      3546
276814    277828
276820      3462
276822    276726
dtype: int64

## Recommendation Results

In [21]:
df[(df['Id']==276820) | (df['Id']==3462)]

Id                                               Book  Rating
54    276820                                 All the King's Men       9
6693    3462                                  Convergent Series       9
6694    3462                                The Barsoom Project       9
6695    3462  Star Trek III The Search for Spock (Star Trek,...       9
6696    3462                                    Dancers of Arun       8
6697    3462                                  PROMETHEUS DESIGN      10
6698    3462                       Star Trek the New Voyages #2       8
6699    3462                                Alchemy and Academe       8

In [22]:
df[(df['Id']==276747) | (df['Id']==276726)]

Id                                               Book  Rating
0   276726                                Classical Mythology       5
7   276747                                    PLEADING GUILTY       9
8   276747  Under the Black Flag: The Romance and the Real...       9
9   276747            Where You'll Find Me: And Other Stories       8
10  276747                        Nights Below Station Street       7
11  276747  Hitler's Secret Bankers: The Myth of Swiss Neu...       7

### Conclusions

1.Recommend the book 'All the King's Men' to userId 3462

2.Recommend the book 'Classical Mythology' to userId 276747

## End